# permissions for end users to view omjis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: omji-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operatorfirst
    app.kubernetes.io/part-of: operatorfirst
    app.kubernetes.io/managed-by: kustomize
  name: omji-viewer-role
rules:
- apiGroups:
  - api.omjikushwaha.com
  resources:
  - omjis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.omjikushwaha.com
  resources:
  - omjis/status
  verbs:
  - get
