---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - api.omjikushwaha.com
  resources:
  - omjis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.omjikushwaha.com
  resources:
  - omjis/finalizers
  verbs:
  - update
- apiGroups:
  - api.omjikushwaha.com
  resources:
  - omjis/status
  verbs:
  - get
  - patch
  - update
